config:
  variable: LADY AND GENTLEMAN! WELCOME TO MICROSERVICES!
  
jwt:
  enhance:
    store:
      file: classpath:/enhance/keystore.jks
      password: nguyen
    key:
      alias: nguyen
      password: nguyen
