server:
  port: 8761

spring:  
   application:    name: eureka-discovery
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
